/// Clean Fred Data 
use "${raw}\fred_raw.dta", clear 
gen date = date(datestr,"YMD", 2050)
gen dow = dow(daten)
order daten dow
gen yr= year(date)
/// Drop Weekends 
drop if dow == 0 | dow == 6 
mdesc 
describe 
tsset daten

//// Grouping Variables 
/// BOFA Corporate
global bofa_all BAMLEM1BRRAAA2ACRPIEY BAMLEM1RAAA2ALCRPIUSEY BAMLEM2BRRBBBCRPIEY BAMLEM2RBBBLCRPIUSEY BAMLEM3BRRBBCRPIEY BAMLEM3RBBLCRPIUSEY BAMLEM4BRRBLCRPIEY BAMLEM4RBLLCRPIUSEY BAMLEM5BCOCRPIEY BAMLEMALLCRPIASIAUSEY BAMLEMCBPIEY BAMLEMCLLCRPIUSEY BAMLEMEBCRPIEEY BAMLEMELLCRPIEMEAUSEY BAMLEMFLFLCRPIUSEY BAMLEMFSFCRPIEY BAMLEMHBHYCRPIEY BAMLEMHGHGLCRPIUSEY BAMLEMHYHYLCRPIUSEY BAMLEMLLLCRPILAUSEY BAMLEMNSNFCRPIEY BAMLEMPBPUBSICRPIEY BAMLEMPTPRVICRPIEY BAMLEMRACRPIASIAEY BAMLEMRECRPIEMEAEY BAMLEMUBCRPIUSEY BAMLEMRLCRPILAEY BAMLH0A0HYM2EY BAMLH0A1HYBBEY BAMLH0A2HYBEY BAMLH0A3HYCEY BAMLHE00EHYIEY BAMLC0A4CBBBEY BAMLC0A1CAAAEY BAMLC0A2CAAEY BAMLC0A0CMEY BAMLC0A3CAEY BAMLC1A0C13YEY BAMLC2A0C35YEY BAMLC3A0C57YEY BAMLC4A0C710YEY BAMLC7A0C1015YEY BAMLC8A0C15PYEY

global bofa_corp_rat BAMLC0A4CBBBEY BAMLC0A1CAAAEY BAMLC0A2CAAEY BAMLC0A0CMEY BAMLC0A3CAEY
global bofa_corp_mat BAMLC1A0C13YEY BAMLC2A0C35YEY BAMLC3A0C57YEY BAMLC4A0C710YEY BAMLC7A0C1015YEY BAMLC8A0C15PYEY

/// Stock Indices
global equity SP500 DJIA NASDAQCOM NASDAQ100 DJTA DJCA DJUA

/// Stocks Wilshire -- ONLY TOTAL MARKET INDICES, NOT PRICE INDICES 
global wilshire WILL5000INDFC WILL5000IND WILLREITIND WILLSMLCAP WILLLRGCAP WILLMICROCAP WILLMIDCAP WILLSMLCAPVALPR WILLRESIND WILLMIDCAPVAL WILL2500INDGR WILL4500IND WILL2500INDVAL WILLMIDCAPGR WILL2500IND

/// Commercial Paper 
global commercial DCPF3M RIFSPPNA2P2D90NB RIFSPPFAAD90NB DCPN3M RIFSPPNAAD90NB RIFSPPNA2P2D30NB DCPF1M RIFSPPAAAD90NB RIFSPPNAAD30NB RIFSPPAAAD30NB RIFSPPNA2P2D01NB RIFSPPFAAD30NB RIFSPPFAAD07NB RIFSPPFAAD01NB DCPN30 RIFSPPNAAD01NB RIFSPPFAAD15NB RIFSPPNAAD60NB RIFSPPAAAD01NB RIFSPPNA2P2D60NB RIFSPPNAAD07NB RIFSPPFAAD60NB RIFSPPNA2P2D07NB RIFSPPNA2P2D15NB RIFSPPAAAD60NB DCPF2M RIFSPPAAAD07NB RIFSPPNAAD15NB DCPN2M RIFSPPAAAD15NB

/// 30 Year Mortgage Indices 
global mortgages OBMMIJUMBO30YF OBMMIC30YFLVLE80FGE740 OBMMIC30YF OBMMIFHA30YF OBMMIUSDA30YF OBMMIVA30YF OBMMIC30YFLVGT80FGE740 OBMMIC30YFLVGT80FB720A739 OBMMIC15YF OBMMIC30YFNA OBMMIC30YFLVGT80FLT680 OBMMIC30YFLVLE80FB700A719 OBMMIC30YFLVLE80FB720A739 OBMMIC30YFLVGT80FB700A719 OBMMIC30YFLVLE80FLT680 OBMMIC30YFLVLE80FB680A699 OBMMIC30YFLVGT80FB680A699 


//// Volatility Indices
global cboe_volatility VIXCLS GVZCLS VXVCLS VXFXICLS OVXCLS VXOCLS RVXCLS VXNCLS VXEEMCLS VXSLVCLS VXDCLS EVZCLS VXXLECLS VXAZNCLS VXEWZCLS VXAPLCLS VXGDXCLS VXGOGCLS VXGSCLS VXIBMCLS

/// Currencies 
global currencies DEXUSEU DEXCHUS DEXJPUS DEXKOUS DEXUSUK DEXMXUS DEXCAUS DTWEXAFEGS DEXINUS DEXBZUS DTWEXEMEGS DEXUSAL DEXVZUS DEXTHUS DEXSFUS DEXSZUS DEXMAUS DEXHKUS DEXNOUS DEXSIUS DEXTAUS DEXSDUS DEXUSNZ DEXSLUS DEXDNUS

/// Energy Commodities 
global energy DCOILWTICO DCOILBRENTEU DHHNGSP DPROPANEMBTX DDFUELUSGULF DHOILNYH DJFUELUSGULF DGASUSGULF DDFUELNYH DGASNYH DDFUELLA DRGASLA

/// Cryptos 
global crypto CBBTCUSD CBETHUSD CBLTCUSD CBBCHUSD

/// Commercial Paper Data Has Several Missings, therefore is not reliable and wont be used 
mdesc $commercial if yr == 2019 | yr == 2020

/// Grouping all the Variables 
global all $bofa_all $equity $wilshire $mortgages $cboe_volatility $currencies $energy $crypto 
mdesc $all if yr == 2019 | yr == 2020

/// Keep only the Variables that we will use 
keep date yr $all 
keep if yr == 2019 | yr == 2020
/// We end up with 145 variables 
describe 
save "${tem}\fred_clean.dta", replace 